<?php 
$link = $this->Html->getLink('empresa/index/index'); 
$linkpag = $this->Html->getLink('pagamento/produto/index');
?>
<br><br><br>
<div class="col-xs-2"> </div>
<div class="col-xs-8">
    <div class='information'>
<b>Parabéns!</b> você acaba de receber <b>30 dias grátis</b> para usufruir de todo o sistema. 
Após os 30 dias você poderá 
adquirir o pacote Profissional por apenas R$99,90/ano ou será automáticamente recondicionado para 
o pacote básico. Qualquer dúvida estamos a disposição em <b>contato@finance-e.com</b>.</div><br><br>
<div class="col-xs-12"> 
<a class="btn btn-large btn-info col-xs-6" href="<?php echo $link; ?>">Quero continuar utilizando gratuitamente</a>
<a class="btn btn-large btn-success col-xs-6" href="<?php echo $linkpag; ?>">Quero assinar pacote anual agora</a>
</div>
</div>
