<style>
    h4{font-size:20px;
       line-height: 30px;
       text-rendering: optimizelegibility;
       text-align:justify;
       margin: 20px 0 0 20px;
       font-weight: normal;
    }
    h1{font-size:40px;line-height: 50px;}
    img{float:left;}
    

</style>
<h1>GERENCIADOR DE INVESTIMENTOS - com calculadora de impostos</h1>
<br>
<div class="span6">
    <h4>Depois do sucesso do sistema de análise de ações disponível em <a href='www.finance-e.com/empresa'>www.finance-e.com/empresa</a>, 
        a Finance-e lança a oportunidade exclusiva para 100 pessoas adquirirem o direito de uso 
        de um sistema de gerenciamento universal de investimentos por <b>tempo ilimitado</b>.</h4>
    <h4>
        Para garantir o atendimento das necessidades dos usuários, garantimos os recursos <b>mínimos</b> do sistema, a saber: <br>
        1.Histórico das operações realizadas;<br>
        2.Lucros/prejuízos por operação;<br>
        3.Posição consolidada em carteira;<br>
        4.Evolução do patrimônio;<br>
        5.Cálculo automatizado de impostos;<br>
        6.Geração de DARF  em um clique;<br>
        7.Opção de upload da nota de corretagem para adicionar novas operações.<br>
    </h4>
</div>
<div class="span6">
    <h4>O início da execução do projeto será:
        Quando 100 pessoas finalizarem a compra do produto, ou, dia 01 de maio de 2014.</h4>

    <h4>Garantimos por meio deste que o projeto será executado em no mínimo 180 dias, 
        com possibilidade de multa por atraso.</h4>
    <h4><a class="btn btn-success btn-large" href="https://www.hotmart.net.br/order/checkout/pay.html?order=P1605223P&cid=236803">Comprar Agora!</a></h4>
    <h4>Maiores informações ligue: (31)9110-3894 ou (31)9449-4408 ou (31)3771-6322</h4>
    <h4>E-mail de contato: pauloveneroso@finance-e.com</h4>
</div>
<div class="span11">
    <h1>Projeto</h1>
    <?php $this->Html->LoadImage('projetogi.png'); ?>
    <h1>Por que comprar?</h1>
    <h4>Com um gerenciador de investimentos o usuário tem a oportunidade de controlar melhor os seus investimentos para que foque seu precioso tempo no que mais gosta.
        E essa oportunidade é única: R$99,90 por direito de uso por tempo ilimitado é para os 100 primeiros compradores. Para os demais cobraremos uma taxa mensal de R$14,90 ao mês.</h4>
    <br>
    
    <h1>O que já falaram da gente:</h1><br>
    <?php $this->Html->LoadImage('Evandrocirc.png'); ?>
    <h4>"[...]Competência da equipe, bem formados e com experiência e sucesso nas suas respectivas áreas de atuação." <u>Evandro Castro - <i>Investidor e Me. em Economia</i></u></h4>
    <br><br>

    <?php $this->Html->LoadImage('gerentecirc.png'); ?>
    <h4>"Site de fácil visualização, com busca rápida e precisa, com vários recursos, não sendo necessários baixar qualquer tipo de software. Estão de parabéns." <u>Paulo Henrique Cabral - <i>Gerente do Banco do Brasil</i></u></h4>
    <br><br>

    <?php $this->Html->LoadImage('luizcirc.png'); ?>
    <h4>"[...]para facilitar meus anseios por informação e assessoria no mundo da bolsa de valores." <u>Luiz Participações - <i>Programador e Investidor</i></u></h4>
    <br><br><br>
    
    <h4><a class="btn btn-success btn-large" href="https://www.hotmart.net.br/order/checkout/pay.html?order=P1605223P&cid=236803">Comprar Agora!</a>
        Maiores informações ligue: (31)9110-3894 ou (31)9449-4408 ou (31)3771-6322.
E-mail de contato: pauloveneroso@finance-e.com</h4>
</div>

